### ISSUE TITLE
Add support for jasmine 2

### ISSUE THREAD

**Issue by alextreppass** [axemclion/grunt-saucelabs#109]
[jasmine-jsreporter](https://github.com/detro/jasmine-jsreporter) doesn't seem to support jasmine 2.0.0 yet, but @sclevine submitted a PR which seems to have done most of the heavy lifting - see https://github.com/detro/jasmine-jsreporter/pull/7

I can get sauce running the tests by including the modified jasmine-jsreporter inside our Gruntfile's [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) vendor section, which overwrites the JSReporter from grunt-saucelabs, and namespaces `window.jasmine.getJSReport()`.

The screencast then says "625 specs, 0 failures, 9 pending specs" and is green/passing, and the selenium log says all suites and specs are passing, however sauce (or grunt-saucelabs?) is saying the tests haven't passed. Going to the JSUnitTest tab on the sauce job however tells me `Jasmine run on Sauce failed: 0 total: 0 passed: 0`, `finished in s`, and `Passing 0 tests`.

Is Jasmine 2 support on the grunt-saucelabs roadmap? If so what are the blockers currently?

**Comment by alexan** [comment]
I've tried to implement your pseudo code
````
(function () {
   var oldFunc = window.jasmine.getJSReport;
   window.jasmine.getJSReport = function () {
      var results = oldFunc();
      return {
         durationSec: results.durationSec,
         suites: removePassingTests(results.suites),
         passed: results.passed
      };
   };


   function removePassingTests(suites) {
      return $.grep($.map(suites, mapSuite), grepFailed);
   }

   function mapSuite(suite) {
      return {
         durationSec: suite.durationSec,
         description: suite.description,
         duration: suite.duration,
         passed: suite.passed,
         failedExpectations: suite.failedExpectations,
         startTime: suite.startTime,
         status: suite.status,
         specs: $.grep(suite.specs, grepFailed),
         suites: removePassingTests(suite.suites)
      };
   }

   function grepFailed(item) {
      return !item.passed;
   }
})();
```
but this dosen't work:
````
=> Starting Tunnel to Sauce Labs
>> Connected to Saucelabs

 1 / 1 tests started


Tested http://127.0.0.1:8080/_SpecRunner.html
Platform: ,chrome,
Passed: undefined
Url https://saucelabs.com/jobs/a4111fbdd5c442b09503051e036cdba0
>> All tests completed with status true
=> Stopping Tunnel to Sauce Labs
```

and on Saucelab I'm getting:
```
{"jasmine":{"message":"unknown error: Cannot read property 'durationSec' of undefined\n (Session info: chrome=41.0.2272.76)\n (Driver info: chromedriver=2.11.298603 (b247579e8a2339c59884aa4b5ef3dcb00d9aa9f8),platform=Linux 3.13.0-32-generic x86)"}}
```



in chrome debugger I get following output
```
window.jasmine.getJSReport();
{
  "durationSec": 0.291,
  "suites": [
    {
      "durationSec": 0.012,
      "description": "EventBus",
      "duration": 12,
      "passed": false,
      "failedExpectations": [],
      "startTime": 1428477306737,
      "status": "finished",
      "specs": [],
      "suites": [
        {
          "durationSec": 0.012,
          "description": "when one listener is registered",
          "duration": 12,
          "passed": false,
          "failedExpectations": [],
          "startTime": 1428477306737,
          "status": "finished",
          "specs": [],
          "suites": [
            {
              "durationSec": 0.003,
              "description": "when second listener is registered",
              "duration": 3,
              "passed": false,
              "failedExpectations": [],
              "startTime": 1428477306746,
              "status": "finished",
              "specs": [
                {
                  "description": "should call every registered listener",
                  "pendingReason": "",
                  "startTime": 1428477306746,
                  "duration": 3,
                  "durationSec": 0.003,
                  "skipped": false,
                  "passed": false,
                  "totalCount": 3,
                  "passedCount": 2,
                  "failedCount": 1,
                  "failures": [
                    {
                      "type": "expect",
                      "expected": [],
                      "passed": false,
                      "message": "Expected true to be falsy.",
                      "matcherName": "toBeFalsy",
                      "trace": {
                        "stack": "Error: Expected true to be falsy.\n    at stack (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1455:17)\n    at buildExpectationResult (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1425:14)\n    at Spec.expectationResultFactory (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:572:18)\n    at Spec.addExpectationResult (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:321:34)\n    at Expectation.addExpectationResult (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:516:21)\n    at Expectation.wrapCompare [as toBeFalsy] (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1379:12)\n    at Object.<anonymous> (http://127.0.0.1:58096/test/specs/eventBusSpec.js:110:26)\n    at attemptSync (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1741:24)\n    at QueueRunner.run (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1729:9)\n    at QueueRunner.execute (http://127.0.0.1:58096/.grunt/grunt-contrib-jasmine/jasmine.js:1714:10)"
                      }
                    }
                  ]
                }
              ],
              "suites": []
            }
          ]
        }
      ]
    }
  ],
  "passed": false
}
```

**Comment by leeyeh** [comment]
@alexan Thanks, You save my time.

**Comment by gordonwoodhull** [comment]
FWIW, ES5-only no-jquery version of @alexan's solution for trimming the passing tests:

```js
jasmine.getEnv().addReporter(new jasmine.JSReporter2());

(function () {
    var oldJSReport = window.jasmine.getJSReport;
    window.jasmine.getJSReport = function () {
        var results = oldJSReport();
        if (results) {
            return {
                durationSec: results.durationSec,
                suites: removePassingTests(results.suites),
                passed: results.passed
            };
        } else {
            return null;
        }
    };

    function removePassingTests (suites) {
        return suites.filter(specFailed)
            .map(mapSuite);
    }

    function mapSuite (suite) {
        var result = {};
        for (var s in suite) {
            result[s] = suite[s];
        }
        result.specs = suite.specs.filter(specFailed);
        result.suites = removePassingTests(suite.suites);
        return result;
    }

    function specFailed (item) {
        return !item.passed;
    }
})();
```
