### ISSUE TITLE
Post to status endpoint is failing

### ISSUE THREAD

**Issue by stdavis** [axemclion/grunt-saucelabs#193]
I just started getting an error message today when I try to run my tests:

```
Running "saucelabs-jasmine:all" (saucelabs-jasmine) task
Verifying property saucelabs-jasmine.all exists in config...OK
File: [no files]
Options: username="agrc-deq-enviro", key="7dc40761-116d-426a-b9a4-6618bfaa43ad", tunneled, identifier="203716605", pollInterval=2000, statusCheckAttempts=500, testname="deq-enviro", browsers=[{"browserName":"safari","platform":"OS X 10.10"},{"browserName":"firefox","platform":"Windows 8.1"},{"browserName":"chrome","platform":"Windows 8.1"},{"browserName":"internet explorer","platform":"Windows 8.1","version":"11"},{"browserName":"internet explorer","platform":"Windows 8","version":"10"},{"browserName":"internet explorer","platform":"Windows 7","version":"9"}], tunnelArgs=[], sauceConfig={"max-duration":10800}, maxRetries=10, urls=["http://127.0.0.1:8000/_SpecRunner.html"], tunnelTimeout=120, build="67088712", maxPollRetries=10, throttled=5
=> Starting Tunnel to Sauce Labs
=> Sauce Labs trying to open tunnel
>> => Sauce Labs Tunnel established
>> Connected to Saucelabs
 1 / 6 tests started
 2 / 6 tests started
 3 / 6 tests started
 4 / 6 tests started
 5 / 6 tests started
 6 / 6 tests started
=> Stopping Tunnel to Sauce Labs
>> 
>> Sauce Labs Tunnel disconnected
>> Error: POST https://saucelabs.com/rest/v1/agrc-deq-enviro/js-tests/status failed.
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:97:15
>>     at _rejected (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:830:24)
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:856:30
>>     at Promise.when (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:1108:31)
>>     at Promise.promise.promiseDispatch (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:774:41)
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:590:44
>>     at runSingle (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:123:13)
>>     at flush (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:111:13)
>>     at process._tickCallback (node.js:419:13)
>>     Error: HTTP error (504)
>>         at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:91:17
>>     From previous event:
>>         at Object.makeRequest (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:86:8)
>>         at fetch (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/Job.js:141:10)
```

Any ideas what's going on?

**Comment by Jonahss** [comment]
Huh. It's been working fine for you for a while, and now this is happening?

It looks like the Tunnel was closed before the tests finished, that could be the issue.

Are you using the latest version of grunt-saucelabs?

**Comment by stdavis** [comment]
Yes, I'm on the latest version. I just restarted the test today and it ran successfully without any changes: https://travis-ci.org/agrc/deq-enviro/builds/67045208

Not sure what's going on. Maybe issues on sauce's end.

**Comment by Jonahss** [comment]
Your test run could have coincided with a service outage. If it happens again please comment on this issue and I'll contact the team that manages the REST api.

**Comment by stdavis** [comment]
It's happening again today. :(

```

Running "saucelabs-jasmine:all" (saucelabs-jasmine) task
Verifying property saucelabs-jasmine.all exists in config...OK
File: [no files]
Options: username="agrc-deq-enviro", key="7dc40761-116d-426a-b9a4-6618bfaa43ad", tunneled, identifier="218758199", pollInterval=2000, statusCheckAttempts=500, testname="deq-enviro", browsers=[{"browserName":"safari","platform":"OS X 10.10"},{"browserName":"firefox","platform":"Windows 8.1"},{"browserName":"chrome","platform":"Windows 8.1"},{"browserName":"internet explorer","platform":"Windows 8.1","version":"11"},{"browserName":"internet explorer","platform":"Windows 8","version":"10"},{"browserName":"internet explorer","platform":"Windows 7","version":"9"}], tunnelArgs=[], sauceConfig={"max-duration":10800}, maxRetries=10, urls=["http://localhost:8001_SpecRunner.html"], tunnelTimeout=120, build="95451597", maxPollRetries=10, throttled=5
=> Starting Tunnel to Sauce Labs
=> Sauce Labs trying to open tunnel
>> => Sauce Labs Tunnel established
>> Connected to Saucelabs
 1 / 6 tests started
 2 / 6 tests started
 3 / 6 tests started
 4 / 6 tests started
 5 / 6 tests started
 6 / 6 tests started
=> Stopping Tunnel to Sauce Labs
>> 
>> Sauce Labs Tunnel disconnected
>> Error: POST https://saucelabs.com/rest/v1/agrc-deq-enviro/js-tests failed.
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:97:15
>>     at _rejected (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:830:24)
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:856:30
>>     at Promise.when (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:1108:31)
>>     at Promise.promise.promiseDispatch (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:774:41)
>>     at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:590:44
>>     at runSingle (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:123:13)
>>     at flush (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/node_modules/q/q.js:111:13)
>>     at process._tickCallback (node.js:419:13)
>>     Error: HTTP error (400)
>>         at /home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:91:17
>>     From previous event:
>>         at Object.makeRequest (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/utils.js:86:8)
>>         at Job.start (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/Job.js:86:8)
>>         at getResult (/home/travis/build/agrc/deq-enviro/node_modules/grunt-saucelabs/src/TestRunner.js:113:10)
Warning: Task "saucelabs-jasmine:all" failed. Use --force to continue.
Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
The command "npm test" exited with 1.
cache.2
store build cache
0.00s2.24snothing changed, not updating cache
Done. Your build exited with 1.
```

http://status.saucelabs.com/ shows all green.
